Avoid AttributeError with PL_version_info
In older versions of libswipl.so, pyswip produced this error:

Traceback (most recent call last):                                                                       
  File "/home/omf/.local/lib/python3.10/site-packages/pyswip/core.py", line 597, in <module>
    if _lib.PL_version_info != None:                                                                     
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__                                
    func = self.__getitem__(name)                                                                        
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))                                                        
AttributeError: /lib/libswipl.so.8: undefined symbol: PL_version_info

We can avoid this by using `hasattr` instead of comparing the property to None.